### ISSUE TITLE
Current path is not always default

### ISSUE THREAD

**Issue by samwilson** [stevedesmond-ca/php-libyear#2]
When invoked as `php ../php-libyear/libyear.php -q` the output is:

```
Gathering information...
PHP Warning:  file_get_contents(-q/composer.json): failed to open stream:
No such file or directory in /[...]/php-libyear/src/FileSystem.php on line 9
```

Which makes sense, but also seems a bit odd because leaving out the path is permitted when the `-q` flat isn't used.

This is with version c627a34137801fdaf6974d88b67d427745cc745f.

**Comment by stevedesmond-ca** [comment]
Thanks for finding this, I had a similar issue with the .NET client. The readme does state that the path parameter is required, but if be happy for a PR that handles a default for quiet mode!
